language: minimal

os: linux
dist: xenial

script:
  - |
    if [[ "$encrypted_529327ce2583_key" == "" ]] || [[ "$encrypted_529327ce2583_iv" == "" ]]; then \
      exit 0; \
    fi; \
  - openssl aes-256-cbc -K $encrypted_529327ce2583_key -iv $encrypted_529327ce2583_iv -in deploy_key.enc -out "$HOME/.ssh/id_rsa" -d
  - git config --global user.email "eli.levy.karin@gmail.com"
  - git config --global user.name "Eli Levy Karin"
  - curl -L https://github.com/gohugoio/hugo/releases/download/v0.55.6/hugo_0.55.6_Linux-64bit.tar.gz | tar xz
  - ./hugo
  - cd public
  - git add .
  - git commit -m "Build website"
  - git push origin master
