name: update website
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'
    - name: Commit files
      run: |
        git config --global user.email "eli.levy.karin@gmail.com"
        git config --global user.name "Eli Levy Karin"
        git clone https://github.com/elileka/elileka.github.io.git public
        curl -L https://github.com/gohugoio/hugo/releases/download/v0.55.6/hugo_0.55.6_Linux-64bit.tar.gz | tar xz
        ./hugo
        cd public
        git add .
        git commit -m "Build website"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: main
        github_token: ${{ secrets.ACTIONS_UPDATE_HOMEPAGE }}
        directory: public
        repository: "https://github.com/elileka/elileka.github.io.git"
